/**
 * The Worker entry point (`main` in wrangler.jsonc). It wraps the OpenNext
 * worker so kan-flare runs without a configured URL, as on a fresh
 * "Deploy to Cloudflare" deploy where the workers.dev address isn't known in
 * advance.
 *
 * When NEXT_PUBLIC_BASE_URL is neither compiled in nor set as a Worker
 * variable, each request uses its own origin. Set NEXT_PUBLIC_BASE_URL once
 * the app has its final address (for example a custom domain), so links in
 * emails and background work always use it.
 */
// Generated by `opennextjs-cloudflare build`.
import handler from "./.open-next/worker.js";

const configured = (env) =>
  typeof env.NEXT_PUBLIC_BASE_URL === "string" &&
  env.NEXT_PUBLIC_BASE_URL.trim() !== "";

export default {
  fetch(request, env, ctx) {
    if (!configured(env)) {
      // OpenNext copies env into process.env only once per isolate, so set
      // the per-request value directly.
      process.env.NEXT_PUBLIC_BASE_URL = new URL(request.url).origin;
    }
    return handler.fetch(request, env, ctx);
  },
};
